/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.project002simplecalculator;

/**
 *
 * @author shawkathsrijon
 */
public class Calculator extends javax.swing.JFrame {
    private double operandOne = 0.0;
    private double operandTwo = 0.0;
    private double result;
    
    private String operator;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }
    /**
     * The displayBackup() method keeps backup from the display that what is entered.
     * @return 
     */
    private String displayBackup(){
        String displayBuffer = displayJTextField.getText();
        return displayBuffer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cancleJButton = new javax.swing.JButton();
        moduleJButton = new javax.swing.JButton();
        divisionJButton = new javax.swing.JButton();
        sevenJButton = new javax.swing.JButton();
        eightJButton = new javax.swing.JButton();
        nineJButton = new javax.swing.JButton();
        multiJButton = new javax.swing.JButton();
        subtractionJButton = new javax.swing.JButton();
        fourJButton = new javax.swing.JButton();
        fiveJButton = new javax.swing.JButton();
        sixJButton = new javax.swing.JButton();
        additionJButton = new javax.swing.JButton();
        threeJButton = new javax.swing.JButton();
        twoJButton = new javax.swing.JButton();
        oneJButton = new javax.swing.JButton();
        equalJButton = new javax.swing.JButton();
        dotJButton = new javax.swing.JButton();
        zeroJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayJTextField.setBackground(new java.awt.Color(77, 76, 75));
        displayJTextField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        displayJTextField.setForeground(new java.awt.Color(255, 255, 255));
        displayJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayJTextFieldActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(117, 115, 113));

        jButton1.setBackground(new java.awt.Color(77, 76, 75));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));

        cancleJButton.setBackground(new java.awt.Color(77, 76, 75));
        cancleJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        cancleJButton.setForeground(new java.awt.Color(255, 255, 255));
        cancleJButton.setText("C");
        cancleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleJButtonActionPerformed(evt);
            }
        });

        moduleJButton.setBackground(new java.awt.Color(77, 76, 75));
        moduleJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        moduleJButton.setForeground(new java.awt.Color(255, 255, 255));
        moduleJButton.setText("%");
        moduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleJButtonActionPerformed(evt);
            }
        });

        divisionJButton.setBackground(new java.awt.Color(255, 165, 31));
        divisionJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        divisionJButton.setForeground(new java.awt.Color(255, 255, 255));
        divisionJButton.setText("/");
        divisionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionJButtonActionPerformed(evt);
            }
        });

        sevenJButton.setBackground(new java.awt.Color(77, 76, 75));
        sevenJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        sevenJButton.setForeground(new java.awt.Color(255, 255, 255));
        sevenJButton.setText("7");
        sevenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenJButtonActionPerformed(evt);
            }
        });

        eightJButton.setBackground(new java.awt.Color(77, 76, 75));
        eightJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        eightJButton.setForeground(new java.awt.Color(255, 255, 255));
        eightJButton.setText("8");
        eightJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightJButtonActionPerformed(evt);
            }
        });

        nineJButton.setBackground(new java.awt.Color(77, 76, 75));
        nineJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        nineJButton.setForeground(new java.awt.Color(255, 255, 255));
        nineJButton.setText("9");
        nineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineJButtonActionPerformed(evt);
            }
        });

        multiJButton.setBackground(new java.awt.Color(255, 165, 31));
        multiJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        multiJButton.setForeground(new java.awt.Color(255, 255, 255));
        multiJButton.setText("*");
        multiJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiJButtonActionPerformed(evt);
            }
        });

        subtractionJButton.setBackground(new java.awt.Color(255, 165, 31));
        subtractionJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        subtractionJButton.setForeground(new java.awt.Color(255, 255, 255));
        subtractionJButton.setText("-");
        subtractionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionJButtonActionPerformed(evt);
            }
        });

        fourJButton.setBackground(new java.awt.Color(77, 76, 75));
        fourJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        fourJButton.setForeground(new java.awt.Color(255, 255, 255));
        fourJButton.setText("4");
        fourJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourJButtonActionPerformed(evt);
            }
        });

        fiveJButton.setBackground(new java.awt.Color(77, 76, 75));
        fiveJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        fiveJButton.setForeground(new java.awt.Color(255, 255, 255));
        fiveJButton.setText("5");
        fiveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveJButtonActionPerformed(evt);
            }
        });

        sixJButton.setBackground(new java.awt.Color(77, 76, 75));
        sixJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        sixJButton.setForeground(new java.awt.Color(255, 255, 255));
        sixJButton.setText("6");
        sixJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixJButtonActionPerformed(evt);
            }
        });

        additionJButton.setBackground(new java.awt.Color(255, 165, 31));
        additionJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        additionJButton.setForeground(new java.awt.Color(255, 255, 255));
        additionJButton.setText("+");
        additionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionJButtonActionPerformed(evt);
            }
        });

        threeJButton.setBackground(new java.awt.Color(77, 76, 75));
        threeJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        threeJButton.setForeground(new java.awt.Color(255, 255, 255));
        threeJButton.setText("3");
        threeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeJButtonActionPerformed(evt);
            }
        });

        twoJButton.setBackground(new java.awt.Color(77, 76, 75));
        twoJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        twoJButton.setForeground(new java.awt.Color(255, 255, 255));
        twoJButton.setText("2");
        twoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoJButtonActionPerformed(evt);
            }
        });

        oneJButton.setBackground(new java.awt.Color(77, 76, 75));
        oneJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        oneJButton.setForeground(new java.awt.Color(255, 255, 255));
        oneJButton.setText("1");
        oneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneJButtonActionPerformed(evt);
            }
        });

        equalJButton.setBackground(new java.awt.Color(255, 165, 31));
        equalJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        equalJButton.setForeground(new java.awt.Color(255, 255, 255));
        equalJButton.setText("=");
        equalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalJButtonActionPerformed(evt);
            }
        });

        dotJButton.setBackground(new java.awt.Color(77, 76, 75));
        dotJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        dotJButton.setForeground(new java.awt.Color(255, 255, 255));
        dotJButton.setText(".");
        dotJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotJButtonActionPerformed(evt);
            }
        });

        zeroJButton.setBackground(new java.awt.Color(77, 76, 75));
        zeroJButton.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        zeroJButton.setForeground(new java.awt.Color(255, 255, 255));
        zeroJButton.setText("0");
        zeroJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moduleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sevenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nineJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fourJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sixJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtractionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oneJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(threeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(additionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(zeroJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dotJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nineJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zeroJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayJTextFieldActionPerformed

    private void fourJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourJButtonActionPerformed
        String buttonFourText = fourJButton.getText();
        displayJTextField.setText(displayBackup() + buttonFourText);
    }//GEN-LAST:event_fourJButtonActionPerformed

    private void eightJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightJButtonActionPerformed
        String buttonEightText = eightJButton.getText();
        displayJTextField.setText(displayBackup() + buttonEightText);
    }//GEN-LAST:event_eightJButtonActionPerformed

    private void dotJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotJButtonActionPerformed

    private void oneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneJButtonActionPerformed
        String buttonOneText = oneJButton.getText();
        displayJTextField.setText(displayBackup() + buttonOneText);
    }//GEN-LAST:event_oneJButtonActionPerformed

    private void twoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoJButtonActionPerformed
        String buttonTwoText = twoJButton.getText();
        displayJTextField.setText(displayBackup() + buttonTwoText);
    }//GEN-LAST:event_twoJButtonActionPerformed

    private void threeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeJButtonActionPerformed
        String buttonThreeText = threeJButton.getText();
        displayJTextField.setText(displayBackup() + buttonThreeText);
    }//GEN-LAST:event_threeJButtonActionPerformed

    private void fiveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveJButtonActionPerformed
        String buttonFiveText = fiveJButton.getText();
        displayJTextField.setText(displayBackup() + buttonFiveText);
    }//GEN-LAST:event_fiveJButtonActionPerformed

    private void sixJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixJButtonActionPerformed
        String buttonSixText = sixJButton.getText();
        displayJTextField.setText(displayBackup() + buttonSixText);
    }//GEN-LAST:event_sixJButtonActionPerformed

    private void sevenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenJButtonActionPerformed
        String buttonSevenText = sevenJButton.getText();
        displayJTextField.setText(displayBackup() + buttonSevenText);
    }//GEN-LAST:event_sevenJButtonActionPerformed

    private void nineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineJButtonActionPerformed
        String buttonNineText = nineJButton.getText();
        displayJTextField.setText(displayBackup() + buttonNineText);
    }//GEN-LAST:event_nineJButtonActionPerformed

    private void zeroJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroJButtonActionPerformed
        String buttonZeroText = zeroJButton.getText();
        displayJTextField.setText(displayBackup() + buttonZeroText);
    }//GEN-LAST:event_zeroJButtonActionPerformed

    private void cancleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleJButtonActionPerformed
        displayJTextField.setText("");
    }//GEN-LAST:event_cancleJButtonActionPerformed

    private void additionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionJButtonActionPerformed
        operandOne = Double.parseDouble(displayJTextField.getText());
        operator = additionJButton.getText();
        displayJTextField.setText("");
    }//GEN-LAST:event_additionJButtonActionPerformed

    private void equalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalJButtonActionPerformed
        operandTwo = Double.parseDouble(displayJTextField.getText());
        char singleOperator = operator.charAt(0);
        
        switch(singleOperator){
            case '+':
                result = operandOne + operandTwo;
                break;
            case '-':
                result = operandOne - operandTwo;
                break;
            case '*':
                result = operandOne * operandTwo;
                break;
            case '/':
                result = operandOne * operandTwo;
                break;
            case '%':
                result = operandOne % operandTwo;
                break;
        }
        
        displayJTextField.setText(String.valueOf(result));
    }//GEN-LAST:event_equalJButtonActionPerformed

    private void subtractionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionJButtonActionPerformed
        operandOne = Double.parseDouble(displayJTextField.getText());
        operator = subtractionJButton.getText();
        displayJTextField.setText("");
    }//GEN-LAST:event_subtractionJButtonActionPerformed

    private void multiJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiJButtonActionPerformed
        operandOne = Double.parseDouble(displayJTextField.getText());
        operator = multiJButton.getText();
        displayJTextField.setText("");
    }//GEN-LAST:event_multiJButtonActionPerformed

    private void divisionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionJButtonActionPerformed
        operandOne = Double.parseDouble(displayJTextField.getText());
        operator = divisionJButton.getText();
        displayJTextField.setText("");
    }//GEN-LAST:event_divisionJButtonActionPerformed

    private void moduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleJButtonActionPerformed
        operandOne = Double.parseDouble(displayJTextField.getText());
        operator = moduleJButton.getText();
        displayJTextField.setText("");
    }//GEN-LAST:event_moduleJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionJButton;
    private javax.swing.JButton cancleJButton;
    private javax.swing.JTextField displayJTextField;
    private javax.swing.JButton divisionJButton;
    private javax.swing.JButton dotJButton;
    private javax.swing.JButton eightJButton;
    private javax.swing.JButton equalJButton;
    private javax.swing.JButton fiveJButton;
    private javax.swing.JButton fourJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moduleJButton;
    private javax.swing.JButton multiJButton;
    private javax.swing.JButton nineJButton;
    private javax.swing.JButton oneJButton;
    private javax.swing.JButton sevenJButton;
    private javax.swing.JButton sixJButton;
    private javax.swing.JButton subtractionJButton;
    private javax.swing.JButton threeJButton;
    private javax.swing.JButton twoJButton;
    private javax.swing.JButton zeroJButton;
    // End of variables declaration//GEN-END:variables
}
